- name: about loops 
  hosts: local 
  connection: local 
  tasks:
   - name: setting loops 
     ansible.builtin.debug: 
      msg: "{{ item }}"
     loop:
      - Ramesh 
      - suresh 
      - Prabha
      - eshwar

- name: about loops 
  hosts: node1 
  become: yes 
  tasks:
   - name: install nginx,mysql,postfix and httpd 
     ansible.builtin.package:
      name: "{{ item }}"
      state: absent
     loop:
      - nginx 
      - mysql 
      - postfix 
      - httpd 
      