- name: variables to print
  hosts: node1 
  vars:
    NAME: Rajesh
    AGE: 27 
    JOB: Engineer 
  tasks:
   - name: print the information 
     debug:
      msg: "Hi my name is {{NAME}}, age is {{ AGE }}, I am an {{ JOB }}"
   
- name: variables from prompt 
  hosts: node2 
  vars_prompt:
   - name: MOBILE_NAME
     prompt: "Eter your mobile name"
     private: false

   - name: Mobile_num 
     prompt: "Enter your mobile number"
     private: true 
     
  tasks:
   - name: userinfo 
     ansible.builtin.debug:
      msg: "your mobile name is {{ MOBILE_NAME }}, Your Mobile Num is {{ Mobile_num }}"

  
