- name: example of filters or function
  hosts: local
  connection: local 
  tasks:
   - name: print the defult varaible
     ansible.builtin.debug:
      msg: "Hello {{ course | default('Ansible') }}"
   
   - name: make uppercase string 
     vars:
      greetings: "RaMesh"
     ansible.builtin.debug:
      msg: "Hello {{ greetings | upper }}" #here upper is function
  
   - name: make uppercase string 
     vars:
      greetings: "RaMesh"
     ansible.builtin.debug:
      msg: "Hello {{ greetings | lower }}" #here lower is function

   - name: To get a unique set from a list
     vars:
      list1: [1, 2, 5, 1, 3, 4, 10]
     ansible.builtin.debug:
      msg: "here is the unique {{ list1 | unique }}" #here unique function
    
   - name: to find min and max from two lists 
     vars: 
      lista: [2, 7, 9, 87, 56, 56, 0]
      listb: [6, 7, 10, 99, 105, 705, 0, 23]
     ansible.builtin.debug:
      msg: "min value in firstlist {{ lista | min }}, max value in second list {{ listb | max }}"
      
   - name: convert map to list 
     vars:
      fruits: 
       name: "Apple"
       color: "red"
       count: 12
     ansible.builtin.debug:
      msg: "{{ fruits | dict2items }}" #dict2iteams will convert map to list
   
   - name: convert list to map
     vars: 
      fruits:
       - { "Key": "name","value": "Apple" }
       - { "key": "color","value": "Red" }
       - { "key": "count","value": 12 }
     ansible.builtin.debug:
      msg: "{{ fruits | dict2items }}" #here also dict2iteams will convert list to map 