- name: example of filters or function
  hosts: local
  connection: local 
  tasks:
   - name: print the defult varaible
     ansible.builtin.debug:
      msg: "Hello {{ course | defult('Ansible') }}"