- name: install mysqlserver on db
  hosts: database
  become: yes 
  tasks:
   - name: install mysqlserver
     ansible.builtin.package: 
      name: mysql-server
      state: present 

   - name: run mysqlserver
     ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes
