- name: command vs shell 
  hosts: local
  connection: yes
  tasks: 
   - name: execute the commands
     ansible.builtin.command: ls -ltr /home/ec2-user
     register: command
    
   - name: print the user info 
     ansible.builtin.debug: 
      msg: " status : {{ command }}"
       
