- name: command vs shell 
  hosts: local
  connection: local
  tasks: 
   - name: execute the commands
     ansible.builtin.command: ls -ltr /home/ec2-user/practice
     register: command
    
   - name: print the info 
     ansible.builtin.debug: 
      msg: "status: {{ command }}" # this is sucess
   
  #  - name: execute the commands
  #    ansible.builtin.command: ls -ltr /home/ec2-user/practice > output.txt
  #    register: command_redi
    
  #  - name: print the info 
  #    ansible.builtin.debug: 
  #     msg: "status: {{ command_redi }}" # this is fail beacuse used redirectors is used by shell not command.
  #     #"rc": 2, "start": "2025-01-22 17:08:24.695481", "stderr": "ls: cannot access '>'
  
   - name: execute the shell 
     ansible.builtin.shell: ls -ltr > /tmp/output.txt
     register: command_redi # it will work as login to the server and execute command inside
    # command module, just issues the command

   - name: check the process
    ansible.builtin.shell: ps -ef | grep ssh
    register: output   # it will sucess because using shell where it have access pipe |

  - name: check the process
    ansible.builtin.command: ps -ef | grep ssh
    register: output   # it will faill beasue here pipe | is used dont have access